name: CPKL_GPytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - colorama=0.4.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.15.0
  - ipython=8.10.0
  - jedi=0.18.2
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=3.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.14.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pywin32=227
  - pyzmq=23.2.0
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tornado=6.2
  - traitlets=5.9.0
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.6
  - wheel=0.38.4
  - wincertstore=0.2
  - zeromq=4.3.4
  - zipp=3.14.0
  - pip:
    - charset-normalizer==3.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - dill==0.3.6
    - et-xmlfile==1.1.0
    - fonttools==4.38.0
    - gpytorch==1.9.1
    - idna==3.4
    - imageio==2.26.1
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - linear-operator==0.3.0
    - llvmlite==0.39.1
    - mapply==0.1.18
    - matplotlib==3.7.0
    - multiprocess==0.70.14
    - numba==0.56.4
    - numpy==1.23.5
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - pandas==1.5.3
    - pathos==0.3.0
    - pillow==9.4.0
    - pox==0.3.2
    - ppft==1.7.6.6
    - pyparsing==3.0.9
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pytz==2022.7.1
    - requests==2.28.2
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - seaborn==0.12.2
    - threadpoolctl==3.1.0
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - typing-extensions==4.5.0
    - urllib3==1.26.14
    - varstool==2.3.5
